### ISSUE TITLE
`ROOM -h` in network room throws exception

### ISSUE THREAD

**Issue by Kritzefitz** [hifi/heisenbridge#169]
I wanted to try out the new room command. So I went into one of my network rooms and issued the command `ROOM -h`. heisenbridge didn't respond and also didn't update the read marker. Instead the log contained the following stack trace:

```
Okt 30 17:24:58 morty heisenbridge[29633]: ERROR:root:Ignoring exception from room handler. This should be fixed.
Okt 30 17:24:58 morty heisenbridge[29633]: Traceback (most recent call last):
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/local/src/heisenbridge/lib/python3.9/site-packages/heisenbridge/__main__.py", line 149, in _on_mx_event
Okt 30 17:24:58 morty heisenbridge[29633]:     await room.on_mx_event(event)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/local/src/heisenbridge/lib/python3.9/site-packages/heisenbridge/room.py", line 85, in on_mx_event
Okt 30 17:24:58 morty heisenbridge[29633]:     await handler(event)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/local/src/heisenbridge/lib/python3.9/site-packages/heisenbridge/network_room.py", line 528, in on_mx_message
Okt 30 17:24:58 morty heisenbridge[29633]:     await self.commands.trigger(command, tail)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/local/src/heisenbridge/lib/python3.9/site-packages/heisenbridge/command_parse.py", line 95, in trigger
Okt 30 17:24:58 morty heisenbridge[29633]:     await self.trigger_args(args, tail, allowed, forward)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/local/src/heisenbridge/lib/python3.9/site-packages/heisenbridge/command_parse.py", line 76, in trigger_args
Okt 30 17:24:58 morty heisenbridge[29633]:     cmd_args = cmd.parse_args(args)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
Okt 30 17:24:58 morty heisenbridge[29633]:     args, argv = self.parse_known_args(args, namespace)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
Okt 30 17:24:58 morty heisenbridge[29633]:     namespace, args = self._parse_known_args(args, namespace)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 2072, in _parse_known_args
Okt 30 17:24:58 morty heisenbridge[29633]:     start_index = consume_optional(start_index)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 2012, in consume_optional
Okt 30 17:24:58 morty heisenbridge[29633]:     take_action(action, args, option_string)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 1940, in take_action
Okt 30 17:24:58 morty heisenbridge[29633]:     action(self, namespace, argument_values, option_string)
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 1104, in __call__
Okt 30 17:24:58 morty heisenbridge[29633]:     parser.print_help()
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/local/src/heisenbridge/lib/python3.9/site-packages/heisenbridge/command_parse.py", line 28, in print_help
Okt 30 17:24:58 morty heisenbridge[29633]:     raise CommandParserError(self.format_help())
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 2544, in format_help
Okt 30 17:24:58 morty heisenbridge[29633]:     return formatter.format_help()
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 295, in format_help
Okt 30 17:24:58 morty heisenbridge[29633]:     help = self._root_section.format_help()
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 226, in format_help
Okt 30 17:24:58 morty heisenbridge[29633]:     item_help = join([func(*args) for func, args in self.items])
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 226, in <listcomp>
Okt 30 17:24:58 morty heisenbridge[29633]:     item_help = join([func(*args) for func, args in self.items])
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 510, in _format_text
Okt 30 17:24:58 morty heisenbridge[29633]:     return self._fill_text(text, text_width, indent) + '\n\n'
Okt 30 17:24:58 morty heisenbridge[29633]:   File "/usr/lib/python3.9/argparse.py", line 682, in _fill_text
Okt 30 17:24:58 morty heisenbridge[29633]:     return ''.join(indent + line for line in text.splitlines(keepends=True))
Okt 30 17:24:58 morty heisenbridge[29633]: AttributeError: 'tuple' object has no attribute 'splitlines'
```

I have installed heisenbridge v1.4.0 via pip in a virtual environment with python 3.9.2 on Debian Bullseye.

**Comment by hifi** [comment]
Fixed in v1.4.1
