### ISSUE TITLE
IndexError when connecting to the server

### ISSUE THREAD

**Issue by Iipin** [hifi/heisenbridge#186]
Hello,
I stumbled upon following issue when trying to connect to irc.sageru.org:6697 (self-signed TLS). I receive first two lines of MOTD, then get disconnected and the cycle repeats after reconnect.
```
ERROR:asyncio:application protocol failed to receive SSL data
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fac237b10d0>
transport: <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 545, in data_received
    self._app_protocol.data_received(chunk)
  File "/opt/heisenbridge/heisenbridge/irc.py", line 82, in data_received
    super().data_received(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/irc/client_aio.py", line 78, in data_received
    self.connection.process_data(data)
  File "/usr/local/lib/python3.9/site-packages/irc/client_aio.py", line 186, in process_data
    self._process_line(line)
  File "/usr/local/lib/python3.9/site-packages/irc/client.py", line 299, in _process_line
    handler(arguments, command, source, tags)
  File "/usr/local/lib/python3.9/site-packages/irc/client.py", line 366, in _handle_other
    self._handle_event(event)
  File "/usr/local/lib/python3.9/site-packages/irc/client.py", line 376, in _handle_event
    self.reactor._handle_event(self, event)
  File "/opt/heisenbridge/heisenbridge/irc.py", line 291, in _handle_event
    result = handler.callback(connection, event)
  File "/opt/heisenbridge/heisenbridge/network_room.py", line 1275, in on_server_message
    if event.arguments[0].lower() in self.whois_data:
IndexError: list index out of range
```
Thanks!

**Comment by hifi** [comment]
Indeed there was an assumption that didn't work. Fixed in master.

Thanks for reporting!
