### ISSUE TITLE
BUG: Heisenbridge fails on first start attempt (matrix-docker-ansible-deploy)

### ISSUE THREAD

**Issue by roughnecks** [hifi/heisenbridge#233]
Hello,

when I restart my matrix-docker-ansible playbook, heisenbridge fails at first attempt, with the following error message:

```
Jun 13 13:58:04   matrix-heisenbridge[228818]: ERROR:root:Unexpected failure when registering appservice user.
Jun 13 13:58:04   matrix-heisenbridge[228818]: Traceback (most recent call last):
Jun 13 13:58:04   matrix-heisenbridge[228818]:   File "/opt/heisenbridge/heisenbridge/__main__.py", line 464, in run
Jun 13 13:58:04   matrix-heisenbridge[228818]:     await self.api.request(
Jun 13 13:58:04   matrix-heisenbridge[228818]:   File "/usr/local/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
Jun 13 13:58:04   matrix-heisenbridge[228818]:     return await self._send(method, full_url, req_content, query_params, headers or {})
Jun 13 13:58:04   matrix-heisenbridge[228818]:   File "/usr/local/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
Jun 13 13:58:04   matrix-heisenbridge[228818]:     raise make_request_error(
Jun 13 13:58:04   matrix-heisenbridge[228818]: mautrix.errors.request.MatrixUnknownRequestError: 502: <html>
Jun 13 13:58:04   matrix-heisenbridge[228818]: <head><title>502 Bad Gateway</title></head>
Jun 13 13:58:04   matrix-heisenbridge[228818]: <body>
Jun 13 13:58:04   matrix-heisenbridge[228818]: <center><h1>502 Bad Gateway</h1></center>
Jun 13 13:58:04   matrix-heisenbridge[228818]: <hr><center>nginx</center>
Jun 13 13:58:04   matrix-heisenbridge[228818]: </body>
Jun 13 13:58:04   matrix-heisenbridge[228818]: </html>
Jun 13 13:58:04   matrix-heisenbridge[228818]: ERROR:asyncio:Unclosed client session
Jun 13 13:58:04   matrix-heisenbridge[228818]: client_session: <aiohttp.client.ClientSession object at 0x7fc79638f6a0>
Jun 13 13:58:04   matrix-heisenbridge[228818]: ERROR:asyncio:Unclosed connector
Jun 13 13:58:04   matrix-heisenbridge[228818]: connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fc796348e20>, 153826.482624502)]']
Jun 13 13:58:04   matrix-heisenbridge[228818]: connector: <aiohttp.connector.TCPConnector object at 0x7fc79638f460>
Jun 13 13:58:06   systemd[1]: matrix-heisenbridge.service: Main process exited, code=exited, status=1/FAILURE
Jun 13 13:58:06   systemd[1]: matrix-heisenbridge.service: Failed with result 'exit-code'.
Jun 13 13:58:36   systemd[1]: matrix-heisenbridge.service: Scheduled restart job, restart counter is at 1.
Jun 13 13:58:36   systemd[1]: Stopped a bouncer-style Matrix IRC bridge.
Jun 13 13:58:36   systemd[1]: Starting a bouncer-style Matrix IRC bridge...
Jun 13 13:58:36   matrix-heisenbridge[229871]: Error response from daemon: Cannot kill container: matrix-heisenbridge: No such container: matrix-heisenbridge
Jun 13 13:58:36   matrix-heisenbridge[229876]: Error: No such container: matrix-heisenbridge
Jun 13 13:58:36   systemd[1]: Started a bouncer-style Matrix IRC bridge.
Jun 13 13:58:39   matrix-heisenbridge[229881]: Heisenbridge v1.13.0
```

**Comment by strk** [comment]
We are having this exact same problem with Heisenbridge v1.7.1 -- I don't know since when. The backtrace is a little different due to source code differences between versions:
```
Jul 22 04:39:41 matrix python[25743]: Heisenbridge v1.7.1
Jul 22 04:39:41 matrix python[25743]: ERROR:root:Unexpected failure when registering appservice user.
Jul 22 04:39:41 matrix python[25743]: Traceback (most recent call last):
Jul 22 04:39:41 matrix python[25743]:   File "/home/heisenbridge/hbridge/lib/python3.7/site-packages/heisenbridge/__main__.py", line 396, in run
Jul 22 04:39:41 matrix python[25743]:     "username": self.registration["sender_localpart"],
Jul 22 04:39:41 matrix python[25743]:   File "/home/heisenbridge/hbridge/lib/python3.7/site-packages/heisenbridge/matrix.py", line 260, in post_user_register
Jul 22 04:39:41 matrix python[25743]:     return await self.call("POST", "/_matrix/client/r0/register?kind=user", data)
Jul 22 04:39:41 matrix python[25743]:   File "/home/heisenbridge/hbridge/lib/python3.7/site-packages/heisenbridge/matrix.py", line 95, in call
Jul 22 04:39:41 matrix python[25743]:     raise self._matrix_error(ret)
```

Sounds like an issue with the communication with synapse

**Comment by strk** [comment]
It looks like your upstream synapse server is not responding correctly (502 Bad Gateway)
