### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Tropaion** [hifi/heisenbridge#240]
Since a while now, the bridge bot is not working anymore, I'm not sure, but maybe since the last synapse update?
Also tried installing it on a new instance of synapse but isn't working either.
These are the verbose logs I got when starting the bridge and joining a room with it:
```
(mautrix-irc) root@ChatMatrix:/opt/mautrix-irc# python -m heisenbridge -c /opt/mautrix-irc/registration.yaml --verbose
Heisenbridge v1.13.1
INFO:root:We are @heisenbridge:flowerhouse.at
INFO:root:We (@heisenbridge:flowerhouse.at) are not a server admin, inviting puppets is required.
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:17:57:48 +0000] "PUT /transactions/127?access_token=********* HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:root:Got an invite from @fabian:flowerhouse.at
INFO:root:Whitelisted user @fabian:flowerhouse.at invited us, going to accept.
ERROR:root:Failed to create control room.
Traceback (most recent call last):
  File "/opt/mautrix-irc/lib/python3.9/site-packages/heisenbridge/__main__.py", line 268, in _on_mx_event
    await room.save()
  File "/opt/mautrix-irc/lib/python3.9/site-packages/heisenbridge/room.py", line 88, in save
    await self.az.intent.set_account_data("irc", config, self.id)
AttributeError: 'ControlRoom' object has no attribute 'az'
```
Version: {"server_version":"1.65.0","python_version":"3.9.2"}
Heisenbridge version: 1.13.1

**Comment by Tropaion** [comment]
This also appeared now after a while:
```
ERROR:root:Failed to reconfigure room !JwcUKqRKvQWXfigjbh:flowerhouse.at during init, leaving.
Traceback (most recent call last):
  File "/opt/mautrix-irc/lib/python3.9/site-packages/heisenbridge/__main__.py", line 642, in run
    raise Exception("Room validation failed after init")
Exception: Room validation failed after in
```

**Comment by Tropaion** [comment]
With the newest realease 1.14.0 these errors are gone and it looks like the commands are received by the bot, but the bot isn't doing anything, no answer or change whatsover.
```
(mautrix-irc) root@ChatMatrix:/opt/mautrix-irc# python -m heisenbridge -c /opt/mautrix-irc/registration.yaml --verbose
Heisenbridge v1.14.0
INFO:root:We are @heisenbridge:flowerhouse.at
INFO:root:We (@heisenbridge:flowerhouse.at) are not a server admin, inviting puppets is required.
Trying to detect homeserver public endpoint, this might take a while...
INFO:root:Starting presence loop
Fetching joined rooms...
Bridge is in 1 rooms, initializing them...
All valid rooms initialized, connecting network rooms...
Init done with 0 networks connecting, bridge is now running!
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:18:48:58 +0000] "PUT /transactions/162?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:18:49:02 +0000] "PUT /transactions/163?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
```

**Comment by hifi** [comment]
Try v1.14.0, please.

**Comment by hifi** [comment]
Try to re-create the DM with the bot.

**Comment by Tropaion** [comment]
I did:
```
(mautrix-irc) root@ChatMatrix:/opt/mautrix-irc# python -m heisenbridge -c /opt/mautrix-irc/registration.yaml --verbose

Heisenbridge v1.14.0
INFO:root:We are @heisenbridge:flowerhouse.at
INFO:root:We (@heisenbridge:flowerhouse.at) are not a server admin, inviting puppets is required.
Trying to detect homeserver public endpoint, this might take a while...
INFO:root:Starting presence loop
Fetching joined rooms...
Bridge is in 1 rooms, initializing them...
All valid rooms initialized, connecting network rooms...
Init done with 0 networks connecting, bridge is now running!
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:08 +0000] "PUT /transactions/178?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:root:Event handler for m.room.member threw RoomInvalidError, leaving and cleaning up.
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:09 +0000] "PUT /transactions/179?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:22 +0000] "PUT /transactions/180?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:root:Got an invite from @fabian:flowerhouse.at
INFO:root:Whitelisted user @fabian:flowerhouse.at invited us, going to accept.
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:22 +0000] "PUT /transactions/181?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:23 +0000] "PUT /transactions/182?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:23 +0000] "PUT /transactions/183?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:23 +0000] "PUT /transactions/184?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"
INFO:aiohttp.access:127.0.0.1 [19/Aug/2022:19:13:33 +0000] "PUT /transactions/185?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.65.0"```
The previous errors are gone and it looks like the commands are received by the bot, but the bot isn't doing anything, no answer or change whatsover.
