### ISSUE TITLE
error with "status" command

### ISSUE THREAD

**Issue by roughnecks** [hifi/heisenbridge#241]
```
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]: ERROR:root:Ignoring exception from room handler. This should be fixed.
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]: Traceback (most recent call last):
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:   File "/opt/heisenbridge/heisenbridge/__main__.py", line 202, in _on_mx_event
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:     await room.on_mx_event(event)
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:   File "/opt/heisenbridge/heisenbridge/room.py", line 100, in on_mx_event
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:     await handler(event)
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:   File "/opt/heisenbridge/heisenbridge/control_room.py", line 240, in on_mx_message
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:     await self.commands.trigger(command, tail)
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:   File "/opt/heisenbridge/heisenbridge/command_parse.py", line 95, in trigger
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:     await self.trigger_args(args, tail, allowed, forward)
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:   File "/opt/heisenbridge/heisenbridge/command_parse.py", line 79, in trigger_args
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:     await func(cmd_args)
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:   File "/opt/heisenbridge/heisenbridge/control_room.py", line 412, in cmd_status
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]:     users.sort()
Aug 26 20:39:22 pandora.woodpeckersnest.space matrix-heisenbridge[4051808]: TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by ilmari** [comment]
I'm still seeing this same error with version 1.14.6:

```
Dec 09 12:02:59 wobble.ilmari.org python[1190]: ERROR:root:Ignoring exception from room handler. This should be fixed.
Dec 09 12:02:59 wobble.ilmari.org python[1190]: Traceback (most recent call last):
Dec 09 12:02:59 wobble.ilmari.org python[1190]:   File "/var/lib/matrix-synapse/heisenbridge/lib/python3.11/site-packages/heisenbridge/__main__.py", line 229, in _on_mx_event
Dec 09 12:02:59 wobble.ilmari.org python[1190]:     await room.on_mx_event(event)
Dec 09 12:02:59 wobble.ilmari.org python[1190]:   File "/var/lib/matrix-synapse/heisenbridge/lib/python3.11/site-packages/heisenbridge/room.py", line 100, in on_mx_event
Dec 09 12:02:59 wobble.ilmari.org python[1190]:     await handler(event)
Dec 09 12:02:59 wobble.ilmari.org python[1190]:   File "/var/lib/matrix-synapse/heisenbridge/lib/python3.11/site-packages/heisenbridge/control_room.py", line 250, in on_mx_message
Dec 09 12:02:59 wobble.ilmari.org python[1190]:     await self.commands.trigger(command, tail)
Dec 09 12:02:59 wobble.ilmari.org python[1190]:   File "/var/lib/matrix-synapse/heisenbridge/lib/python3.11/site-packages/heisenbridge/command_parse.py", line 95, in trigger
Dec 09 12:02:59 wobble.ilmari.org python[1190]:     await self.trigger_args(args, tail, allowed, forward)
Dec 09 12:02:59 wobble.ilmari.org python[1190]:   File "/var/lib/matrix-synapse/heisenbridge/lib/python3.11/site-packages/heisenbridge/command_parse.py", line 79, in trigger_args
Dec 09 12:02:59 wobble.ilmari.org python[1190]:     await func(cmd_args)
Dec 09 12:02:59 wobble.ilmari.org python[1190]:   File "/var/lib/matrix-synapse/heisenbridge/lib/python3.11/site-packages/heisenbridge/control_room.py", line 423, in cmd_status
Dec 09 12:02:59 wobble.ilmari.org python[1190]:     users.sort()
Dec 09 12:02:59 wobble.ilmari.org python[1190]: TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by Christoph-D** [comment]
The hidden room has `user_id` set to `None`, which trips up the status command when it looks up the list of all users.
