### ISSUE TITLE
[Conduit] needs to handle 404 results to /_synapse calls 

### ISSUE THREAD

**Issue by Peetz0r** [hifi/heisenbridge#69]
It does a request to /_synapse/admin/v1/users/@heisenbridge:c.glitch.im/admin [here](https://github.com/hifi/heisenbridge/blob/master/heisenbridge/__main__.py#L315) which looks like it should work fine when that call fails.

But in reality, when the call is done against Conduit, it tries anyway for half an hour because of [this loop](https://github.com/hifi/heisenbridge/blob/master/heisenbridge/matrix.py#L56)

```
May 28 00:07:28 niks systemd[1]: Started heisenbridge.service.
May 28 00:07:31 niks python[11225]: DEBUG:asyncio:Using selector: EpollSelector
May 28 00:07:31 niks python[11225]: INFO:root:We are @heisenbridge:c.glitch.im
May 28 00:07:31 niks python[11225]: DEBUG:root:Default config: {'networks': {}, 'owner': None, 'allow': {}}
May 28 00:07:31 niks python[11225]: WARNING:root:Request to HS failed, assuming it is down, retry 1/60...
May 28 00:08:01 niks python[11225]: WARNING:root:Request to HS failed, assuming it is down, retry 2/60...
May 28 00:08:31 niks python[11225]: WARNING:root:Request to HS failed, assuming it is down, retry 3/60...
May 28 00:09:01 niks python[11225]: WARNING:root:Request to HS failed, assuming it is down, retry 4/60...
```
(I will keep this running for another 28 minutes and see what happens)

**Comment by Peetz0r** [comment]
(28 minutes later)
```
May 28 00:36:34 niks python[11225]: WARNING:root:Request to HS failed, assuming it is down, retry 59/60...
May 28 00:37:04 niks python[11225]: WARNING:root:Request to HS failed, assuming it is down, retry 60/60...
May 28 00:37:34 niks python[11225]: INFO:root:Seems we are not connected to Synapse, inviting puppets is required.
May 28 00:37:34 niks python[11225]: Homeserver is publicly available at https://conduit.glitch.im
May 28 00:37:34 niks python[11225]: DEBUG:root:Merged configuration from HS: {'networks': {}, 'owner': None, 'allow': {}}
May 28 00:37:34 niks python[11225]: INFO:root:Overriding loaded owner with '@peetz0r:c.glitch.im'
May 28 00:37:34 niks python[11225]: DEBUG:root:Appservice rooms: []
May 28 00:37:34 niks python[11225]: ERROR:root:Unexpected failure when registering appservice user.
May 28 00:37:34 niks python[11225]: Traceback (most recent call last):
May 28 00:37:34 niks python[11225]:   File "/nix/store/1ysbsiwrgy4psi56rnnl2xiw89qdjln7-python3-3.8.9-env/lib/python3.8/site-packages/heisenbridge/__main__.py", line 354, in run
May 28 00:37:34 niks python[11225]:     await self.api.post_user_register(
May 28 00:37:34 niks python[11225]:   File "/nix/store/1ysbsiwrgy4psi56rnnl2xiw89qdjln7-python3-3.8.9-env/lib/python3.8/site-packages/heisenbridge/matrix.py", line 158, in post_user_register
May 28 00:37:34 niks python[11225]:     return await self.call("POST", "/_matrix/client/r0/register?kind=user", data)
May 28 00:37:34 niks python[11225]:   File "/nix/store/1ysbsiwrgy4psi56rnnl2xiw89qdjln7-python3-3.8.9-env/lib/python3.8/site-packages/heisenbridge/matrix.py", line 61, in call
May 28 00:37:34 niks python[11225]:     raise self._matrix_error(data)
May 28 00:37:34 niks python[11225]: heisenbridge.matrix.MatrixForbidden: M_FORBIDDEN: Registration has been disabled.
May 28 00:37:34 niks python[11225]: INFO:root:Connecting network rooms...
May 28 00:37:34 niks python[11225]: INFO:root:Init done, bridge is now running!
```
For the registration error, see #68.

So, now the bridge is actually running. But it doesn't seem to want to join my admin room. Am already digging in deeper.
